#pragma once

static const int ANIMATION_REFRESH_DURATION = 100;
static const int ANIMATION_REFRESH_DURATION_PLAYER_ROLL = 50;
static const int POSITION_REFRESH_DURATION = 10;

static const int PLAYER_MOVE_SPEED = 5;
static const int PLAYER_MOVE_SPEED_DIAGONAL = 4;
static const int PLAYER_ROLL_START_SPEED = 7;
static const int PLAYER_ROLL_ING_SPEED = 3;
static const int PLAYER_ROLL_END_SPEED = 4;
static const int PLAYER_ROLL_START_SPEED_DIAGONAL = 5;
static const int PLAYER_ROLL_ING_SPEED_DIAGONAL = 2;
static const int PLAYER_ROLL_END_SPEED_DIAGONAL = 2;

#pragma region Animation Bitmap Offset
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_UP = { 0, 50 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_DOWN = { 0, 0 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_LEFT = { 0, 25 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_RIGHT = { 0, 25 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_UPLEFT = { 0, 75 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_UPRIGHT = { 0, 75 };

static const POINT ANIMATION_OFFSET_PLAYER_MOVE_UP = { 0, 175 };
static const POINT ANIMATION_OFFSET_PLAYER_MOVE_DOWN = { 0, 125 };
static const POINT ANIMATION_OFFSET_PLAYER_MOVE_LEFT = { 0, 150 };
static const POINT ANIMATION_OFFSET_PLAYER_MOVE_RIGHT = { 0, 150 };
static const POINT ANIMATION_OFFSET_PLAYER_MOVE_UPLEFT = { 0, 200 };
static const POINT ANIMATION_OFFSET_PLAYER_MOVE_UPRIGHT = { 0, 200 };

static const POINT ANIMATION_OFFSET_PLAYER_ROLL_UP = { 0, 275 };
static const POINT ANIMATION_OFFSET_PLAYER_ROLL_DOWN = { 0, 225 };
static const POINT ANIMATION_OFFSET_PLAYER_ROLL_LEFT = { 0, 250 };
static const POINT ANIMATION_OFFSET_PLAYER_ROLL_RIGHT = { 0, 250 };
static const POINT ANIMATION_OFFSET_PLAYER_ROLL_UPLEFT = { 0, 300 };
static const POINT ANIMATION_OFFSET_PLAYER_ROLL_UPRIGHT = { 0, 300 };
#pragma endregion

static const double TAN_22_5 = 0.41421356;
static const double TAN_67_5 = 2.41421356;