#pragma once

static const int PLAYER_MOVE_SPEED = 5;
static const int ANIMATION_REFRESH_DURATION = 100;
static const int POSITION_REFRESH_DURATION = 10;

static const POINT ANIMATION_OFFSET_PLAYER_IDLE_UP = { 0, 50 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_DOWN = { 0, 0 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_LEFT = { 0, 25 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_RIGHT = { 0, 25 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_UPLEFT = { 0, 75 };
static const POINT ANIMATION_OFFSET_PLAYER_IDLE_UPRIGHT = { 0, 75 };
static const POINT ANIMATION_OFFSET_PLAYER_UP = { 0, 175 };
static const POINT ANIMATION_OFFSET_PLAYER_DOWN = { 0, 125 };
static const POINT ANIMATION_OFFSET_PLAYER_LEFT = { 0, 150 };
static const POINT ANIMATION_OFFSET_PLAYER_RIGHT = { 0, 150 };
static const POINT ANIMATION_OFFSET_PLAYER_UPLEFT = { 0, 200 };
static const POINT ANIMATION_OFFSET_PLAYER_UPRIGHT = { 0, 200 };

static const double TAN_22_5 = 0.41421356;
static const double TAN_67_5 = 2.41421356;